window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "API_KEY": "AIzaSyBJkoJ2T8mDb1NT7KCqa7A8Au9SoXA5Fvc",
  "APPDATA": "C:\\Users\\tico\\AppData\\Roaming",
  "APP_ID": "1:471272689107:web:bab20bbe583dbbfc18f326",
  "AUTH_DOMAIN": "birthday-vote.firebaseapp.com",
  "ChocolateyInstall": "C:\\ProgramData\\chocolatey",
  "ChocolateyLastPathUpdate": "132922907378197832",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_18768_WQLEBSLQYPFZABSD",
  "CLIENT_ID": "471272689107-htc3hgbupm00e6r62865mlp619f5gtmu.apps.googleusercontent.com",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "DESKTOP-EELCV2F",
  "ComSpec": "C:\\Windows\\system32\\cmd.exe",
  "DATABASE_URL": "https://birthday-vote-default-rtdb.firebaseio.com",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "notepad.exe",
  "GIT_ASKPASS": "c:\\Users\\tico\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\tico",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\tico",
  "INIT_CWD": "C:\\Users\\tico\\Documents\\workspace\\birthday-vote",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\tico\\AppData\\Local",
  "LOGONSERVER": "\\\\DESKTOP-EELCV2F",
  "MESSAGING_SENDER_ID": "471272689107",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\tico\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\tico\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\tico\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\tico\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\tico\\Documents\\workspace\\birthday-vote",
  "npm_config_metrics_registry": "https://registry.npmjs.org/",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_prefix": "C:\\Users\\tico\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\tico\\.npmrc",
  "npm_config_user_agent": "npm/8.5.0 node/v16.14.2 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "build",
  "npm_lifecycle_script": "react-dotenv && react-scripts build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\tico\\Documents\\workspace\\birthday-vote\\package.json",
  "npm_package_name": "birthday-vote",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\tico\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "4",
  "NVM_HOME": "C:\\Users\\tico\\AppData\\Roaming\\nvm",
  "NVM_SYMLINK": "C:\\Program Files\\nodejs",
  "OneDrive": "C:\\Users\\tico\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\tico\\Documents\\workspace\\birthday-vote\\node_modules\\.bin;C:\\Users\\tico\\Documents\\workspace\\node_modules\\.bin;C:\\Users\\tico\\Documents\\node_modules\\.bin;C:\\Users\\tico\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Users\\tico\\Documents\\workspace\\birthday-vote\\node_modules\\.bin;C:\\Users\\tico\\Documents\\workspace\\node_modules\\.bin;C:\\Users\\tico\\Documents\\node_modules\\.bin;C:\\Users\\tico\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files\\Python311\\Scripts\\;C:\\Program Files\\Python311\\;C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Users\\tico\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Users\\tico\\AppData\\Roaming\\npm\\;C:\\Program Files\\Python311\\Scripts\\;C:\\Program Files\\Python311\\;C:\\Python310\\Scripts\\;C:\\Python310\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Users\\tico\\AppData\\Roaming\\nvm;C:\\Program Files\\nodejs;C:\\Program Files\\nodejs\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\;C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\;C:\\Program Files\\dotnet\\;C:\\Users\\tico\\AppData\\Roaming\\npm\\;;C:\\Users\\tico\\AppData\\Local\\Programs\\Python\\Python311\\python.exe;C:\\Users\\tico\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\tico\\.dotnet\\tools",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 142 Stepping 9, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "8e09",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROJECT_ID": "birthday-vote",
  "PROMPT": "$P$G",
  "PSExecutionPolicyPreference": "Bypass",
  "PSModulePath": "C:\\Users\\tico\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "SESSIONNAME": "Console",
  "STORAGE_BUCKET": "birthday-vote.appspot.com",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\Windows",
  "TEMP": "C:\\Users\\tico\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.83.1",
  "TMP": "C:\\Users\\tico\\AppData\\Local\\Temp",
  "USERDOMAIN": "DESKTOP-EELCV2F",
  "USERDOMAIN_ROAMINGPROFILE": "DESKTOP-EELCV2F",
  "USERNAME": "tico",
  "USERPROFILE": "C:\\Users\\tico",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "--ms-enable-electron-run-as-node",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\tico\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\tico\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-b58ae4d139-sock",
  "windir": "C:\\Windows",
  "ZES_ENABLE_SYSMAN": "1"
};